### ISSUE TITLE
Renaming this repository

### ISSUE THREAD

**Issue by sldblog** [ministryofjustice/laa-architectural-diagrams#36]
We have the https://github.com/ministryofjustice/laa-architectural-decisions repository for decisions, and we have moved our ADRs there.

This repository now only contains diagrams.

What do you think about renaming it to reflect this purpose?

- Decisions: https://github.com/ministryofjustice/laa-architectural-decisions
- Diagrams:
    ```diff
    -https://github.com/ministryofjustice/laa-architecture-documentation
    +https://github.com/ministryofjustice/laa-architectural-diagrams
    ```

**Comment by scruti** [comment]
I think is the right thing to do 👏

**Comment by sldblog** [comment]
Done! :bowing_man:

**Comment by sldblog** [comment]
Caveat:

This rename broke all media links, like this one: https://media.githubusercontent.com/media/ministryofjustice/laa-architecture-documentation/master/diagrams/outside/analytical-platform-containers.png

Not redirecting on media links is unfortunate because I directly linked to the "master" images on Confluence, readmes, pretty much everywhere as it was handy to have them auto-update 😅 

I had to find all the broken images and fix their URL manually.
